# Docker Compose 파일 버전
version: "3.8"

# 실행할 컨테이너(서비스) 정의
services:

  # MariaDB 데이터베이스 서버
  mariadb:
    image: mariadb:11
    container_name: mariadb

    # DB 초기 설정
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: quizdb
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass

    # 호스트 PC의 3306 포트와 컨테이너의 3306 포트 연결
    ports:
      - "3306:3306"

    # SQL 백업 파일 자동 실행을 위한 볼륨 마운트
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  # Flask 백엔드 서버
  flask:
    build: ./flask
    container_name: flask

    # Flask 서버 포트 연결
    ports:
      - "5000:5000"

    # MariaDB가 먼저 실행된 후 Flask 실행
    depends_on:
      - mariadb

  # Nginx 웹 서버
  nginx:
    build: ./nginx
    container_name: nginx

    # 웹 서비스 포트 연결
    ports:
      - "80:80"

    # Flask 서버 실행 후 Nginx 실행
    depends_on:
      - flask
