version: "3.8"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: quizdb
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  flask:
    build: ./flask
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - mariadb

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask