version: "3.8" # Docker Compose 파일 버전
services: # 실행할 컨테이너(서비스) 정의
  mariadb:   # MariaDB 데이터베이스 서버
    image: mariadb:11
    container_name: mariadb
    environment:     # DB 초기 설정
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: quizdb
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass

    ports:     # 호스트 PC의 3306 포트와 컨테이너의 3306 포트 연결
      - "3307:3306"

    volumes:     # SQL 백업 파일 자동 실행을 위한 볼륨 마운트
      - ./db:/docker-entrypoint-initdb.d

  flask:   # Flask 백엔드 서버
    build: ./flask
    container_name: flask

    ports:     # Flask 서버 포트 연결
      - "5000:5000"

    depends_on:     # MariaDB가 먼저 실행된 후 Flask 실행
      - mariadb

  nginx:   # Nginx 웹 서버
    build: ./nginx
    container_name: nginx

    ports:     # 웹 서비스 포트 연결
      - "8080:80"

    depends_on:     # Flask 서버 실행 후 Nginx 실행
      - flask
