server { # 서버 블록 정의
    listen 80; # Nginx가 80번 포트(HTTP 요청)를 수신

    location / { # 모든 URL 요청 처리
        proxy_pass http://flask:5000;  #요청을 Flask 컨테이너의 5000번 포트로 전달
        proxy_set_header Host $host; # 원래 요청의 Host 정보를 Flask에 전달
        proxy_set_header X-Real-IP $remote_addr; # 실제 클라이언트(IP 주소)를 Flask에 전달
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #프록시를 거쳐 온 모든 클라이언트 IP 정보를 전달
    }
}
